from __future__ import annotations

"""Generate build-only metadata embedded by PyInstaller.

The target is ignored by Git so a local source checkout never accidentally
claims to be an official release.
"""

import argparse
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--commit", default="local")
    parser.add_argument("--repository", default="")
    parser.add_argument("--date", default="")
    args = parser.parse_args()
    build_date = args.date.strip() or datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    destination = ROOT / "check_vehicle_ocr" / "_build_meta.py"
    destination.write_text(
        "# Generated by tools/write_build_metadata.py; do not commit.\n"
        f"BUILD_DATE = {build_date!r}\n"
        f"COMMIT_SHA = {args.commit.strip()!r}\n"
        f"GITHUB_REPOSITORY = {args.repository.strip()!r}\n",
        encoding="utf-8",
    )
    print(destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
